---
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: channel-events-local
      PackageType: Zip
      Runtime: python3.13
      CodeUri: ./_bundle.zip
      Handler: handler.handler
      Environment:
        Variables:
          SLACK_SIGNING_SECRET:
          SLACK_API_TOKEN:
          SLACK_NOTIFY_CHANNEL:
      Events:
        HttpApiEvent:
          Type: HttpApi
